In [ ]:
from project_olist.config import RAW_DATA_DIR
import pandas

dataframe_avaliacoes = pandas.read_csv(RAW_DATA_DIR / "olist_order_reviews_dataset.csv")
dataframe_avaliacoes = dataframe_avaliacoes.rename(
    columns={
        "review_id": "id_avaliacao",
        "order_id": "id_pedido",
        "review_score": "pontuacao",
        "review_creation_date": "data_criacao",
        "review_answer_timestamp": "data_resposta"
    }
)

dataframe_avaliacoes = dataframe_avaliacoes.drop(
    columns=["review_comment_title", "review_comment_message"]
)

dataframe_avaliacoes.info()

<class 'pandas.DataFrame'>
RangeIndex: 99224 entries, 0 to 99223
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id_avaliacao   99224 non-null  str
 1   id_pedido      99224 non-null  str
 2   pontuacao      99224 non-null  int64
 3   data_criacao   99224 non-null  str
 4   data_resposta  99224 non-null  str
dtypes: int64(1), str(4)
memory usage: 3.8 MB

In [5]:
dataframe_avaliacoes.sample(n=5)

,id_avaliacao,id_pedido,pontuacao,data_criacao,data_resposta
32575,6a7a8a1a9f55296189b03f533a89c792,6508f1528c3648c8a9f751e811520269,3,2018-02-15 00:00:00,2018-02-15 18:33:22
23984,2efdf07992f8a1f2c932e3a912b4f8b4,098f60afb74eab906fedaf802a833a97,4,2018-01-19 00:00:00,2018-01-21 19:19:38
9789,5598c9c5571557887f8abbae4faeeba6,a6eaa4e9d0e172457c2f76bdd1face86,1,2017-12-08 00:00:00,2017-12-10 07:48:03
89240,b4a0eddb30e2035001f39819798e9d03,ecac9efb8edbf004c521a0cc86b0a167,5,2017-10-10 00:00:00,2017-10-12 15:38:01
83575,37f5d019fbd4122030cac02bcb383906,41929ebe6ccc16768bbe9d5977c470b1,4,2017-10-28 00:00:00,2017-10-28 15:18:29

In [8]:
dataframe_avaliacoes["data_criacao"] = pandas.to_datetime(dataframe_avaliacoes["data_criacao"]).dt.normalize()
dataframe_avaliacoes["data_resposta"] = pandas.to_datetime(dataframe_avaliacoes["data_resposta"]).dt.normalize()

dataframe_avaliacoes.info()

<class 'pandas.DataFrame'>
RangeIndex: 99224 entries, 0 to 99223
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id_avaliacao   99224 non-null  str
 1   id_pedido      99224 non-null  str
 2   pontuacao      99224 non-null  int64
 3   data_criacao   99224 non-null  datetime64[us]
 4   data_resposta  99224 non-null  datetime64[us]
dtypes: datetime64[us](2), int64(1), str(2)
memory usage: 3.8 MB

In [9]:
dataframe_avaliacoes["tempo_resposta_dias"] = (
    (dataframe_avaliacoes["data_resposta"] - dataframe_avaliacoes["data_criacao"]).dt.days
)

dataframe_avaliacoes.sample(n=5)

,id_avaliacao,id_pedido,pontuacao,data_criacao,data_resposta,tempo_resposta_dias
18100,93aab680a2b60f02a936fca80d96b8c0,c40ef1f09f4ba772a63865df0274f6b8,5,2017-04-08,2017-04-08,0
67536,897d74355dff031f4a1ca1c0ef2c1292,43c04de0613b79c2470b22e171cc848d,5,2018-07-25,2018-07-26,1
34545,112cc027137b7e17358806dd9d8c1176,c518733b452a98377e02153098a0542d,5,2017-05-23,2017-05-26,3
40104,3d163199153af414059e6cfabc09a0fd,ca263afd88a8a1200605adbd4b63cd7d,1,2018-04-21,2018-04-23,2
95555,57816f47bc2696680766f2938088af79,63a7f803612d7247f296ef6007668c5b,5,2018-06-29,2018-07-02,3

In [10]:
dataframe_avaliacoes = dataframe_avaliacoes.drop(
    columns=[
        "data_criacao",
        "data_resposta"
    ]
)

dataframe_avaliacoes.info()

<class 'pandas.DataFrame'>
RangeIndex: 99224 entries, 0 to 99223
Data columns (total 4 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   id_avaliacao         99224 non-null  str
 1   id_pedido            99224 non-null  str
 2   pontuacao            99224 non-null  int64
 3   tempo_resposta_dias  99224 non-null  int64
dtypes: int64(2), str(2)
memory usage: 3.0 MB

In [11]:
dataframe_avaliacoes.describe()

          pontuacao  tempo_resposta_dias
count  99224.000000         99224.000000
mean       4.086421             2.582268
std        1.347579             9.890527
min        1.000000             0.000000
25%        4.000000             1.000000
50%        5.000000             1.000000
75%        5.000000             3.000000
max        5.000000           518.000000

In [13]:
from project_olist.config import PROCESSED_DATA_DIR

dataframe_avaliacoes.to_csv(PROCESSED_DATA_DIR / "avaliacoes.csv", index=False)