In [1]:
from project_olist.config import RAW_DATA_DIR
import pandas

dataframe_avaliacoes = pandas.read_csv(RAW_DATA_DIR / "olist_order_reviews_dataset.csv")
dataframe_avaliacoes = dataframe_avaliacoes.rename(
    columns={
        "review_id": "id_avaliacao",
        "order_id": "id_pedido",
        "review_score": "pontuacao",
        "review_creation_date": "data_criacao",
        "review_answer_timestamp": "data_resposta"
    }
)

dataframe_avaliacoes = dataframe_avaliacoes.drop(
    columns=["review_comment_title", "review_comment_message"]
)

dataframe_avaliacoes.info()

<class 'pandas.DataFrame'>
RangeIndex: 99224 entries, 0 to 99223
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id_avaliacao   99224 non-null  str
 1   id_pedido      99224 non-null  str
 2   pontuacao      99224 non-null  int64
 3   data_criacao   99224 non-null  str
 4   data_resposta  99224 non-null  str
dtypes: int64(1), str(4)
memory usage: 3.8 MB

In [2]:
dataframe_avaliacoes.sample(n=5)

,id_avaliacao,id_pedido,pontuacao,data_criacao,data_resposta
13425,0e95954f02747c30208c87719e97b470,e670c857f8a70c9aacdf644c59980d17,5,2018-04-28 00:00:00,2018-04-29 03:27:22
53219,89edecdcc0903c2f28cdfe523e1bbfd7,c1649e916cf1080b2c01bbb3f6078999,5,2018-02-21 00:00:00,2018-02-22 10:30:23
51434,3ac03a9d72255c0a46cef2eb3a62bf9c,3662bd55e74767e3a5f39573beae83b5,5,2018-03-14 00:00:00,2018-03-15 16:33:14
88826,50c851bd79dc0b19f3d9c523ca747df8,54bb06e1ca86bd99ee2a8d6288bf4ede,1,2016-12-14 00:00:00,2016-12-16 09:34:47
4417,25beaef52610f91849c20c74715ac85c,74a11d53ff594d7838a43abf53f0bd32,3,2018-04-21 00:00:00,2018-04-30 15:00:36

In [3]:
dataframe_avaliacoes["data_criacao"] = pandas.to_datetime(dataframe_avaliacoes["data_criacao"]).dt.normalize()
dataframe_avaliacoes["data_resposta"] = pandas.to_datetime(dataframe_avaliacoes["data_resposta"]).dt.normalize()

dataframe_avaliacoes.info()

<class 'pandas.DataFrame'>
RangeIndex: 99224 entries, 0 to 99223
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id_avaliacao   99224 non-null  str
 1   id_pedido      99224 non-null  str
 2   pontuacao      99224 non-null  int64
 3   data_criacao   99224 non-null  datetime64[us]
 4   data_resposta  99224 non-null  datetime64[us]
dtypes: datetime64[us](2), int64(1), str(2)
memory usage: 3.8 MB

In [4]:
dataframe_avaliacoes["tempo_resposta_dias"] = (
    (dataframe_avaliacoes["data_resposta"] - dataframe_avaliacoes["data_criacao"]).dt.days
)

dataframe_avaliacoes.sample(n=5)

,id_avaliacao,id_pedido,pontuacao,data_criacao,data_resposta,tempo_resposta_dias
60927,d70bceb376205914be31d3078474c0a8,915e61444d403c1c57fa206962c3e60f,5,2018-08-14,2018-08-15,1
8741,9649c618b8d78749dc94acddf679831d,dfe9ed7cb28d282f7cb649346e0898c8,5,2018-03-02,2018-03-08,6
15085,86d2a083245a81bd14721e29770c0a46,2ae01dafe3790417726f148d9f1a90a4,5,2018-08-30,2018-08-31,1
12276,747c84e5e680bbd96112027768885d64,4da38cd7084ce9fdeae2412858379255,3,2017-11-09,2017-11-12,3
25819,219cf59cf889bc85babbd1cd1fe30f2d,83018ec114eee8641c97e08f7b4e926f,4,2017-11-09,2017-11-10,1

In [5]:
dataframe_avaliacoes = dataframe_avaliacoes.drop(
    columns=[
        "data_criacao",
        "data_resposta"
    ]
)

dataframe_avaliacoes.info()

<class 'pandas.DataFrame'>
RangeIndex: 99224 entries, 0 to 99223
Data columns (total 4 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   id_avaliacao         99224 non-null  str
 1   id_pedido            99224 non-null  str
 2   pontuacao            99224 non-null  int64
 3   tempo_resposta_dias  99224 non-null  int64
dtypes: int64(2), str(2)
memory usage: 3.0 MB

In [6]:
dataframe_avaliacoes.describe()

          pontuacao  tempo_resposta_dias
count  99224.000000         99224.000000
mean       4.086421             2.582268
std        1.347579             9.890527
min        1.000000             0.000000
25%        4.000000             1.000000
50%        5.000000             1.000000
75%        5.000000             3.000000
max        5.000000           518.000000

In [7]:
dataframe_avaliacoes["cliente_satisfeito"] = dataframe_avaliacoes.apply(
    lambda row: (
        1 if row["pontuacao"] >= 4
        else 0
    ),
    axis=1
)

In [8]:
from project_olist.config import PROCESSED_DATA_DIR

dataframe_avaliacoes.to_csv(PROCESSED_DATA_DIR / "avaliacoes.csv", index=False)