In [12]:
from project_olist.config import RAW_DATA_DIR
import pandas

dataframe_clientes = pandas.read_csv(RAW_DATA_DIR / "olist_customers_dataset.csv")
dataframe_clientes = dataframe_clientes.rename(
    columns={
        "customer_id": "id_cliente",
        "customer_unique_id": "id_unico_cliente",
        "customer_zip_code_prefix": "prefixo_cep",
        "customer_city": "cidade",
        "customer_state": "estado"
    }
)

dataframe_clientes.info()

<class 'pandas.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   id_cliente        99441 non-null  str
 1   id_unico_cliente  99441 non-null  str
 2   prefixo_cep       99441 non-null  int64
 3   cidade            99441 non-null  str
 4   estado            99441 non-null  str
dtypes: int64(1), str(4)
memory usage: 3.8 MB

In [13]:
dataframe_clientes["prefixo_cep"] = dataframe_clientes["prefixo_cep"].astype(str)
dataframe_clientes["prefixo_cep"] = dataframe_clientes["prefixo_cep"].map(
    lambda x: x.rjust(5, "0")
)

In [14]:
dataframe_clientes.sample(n=5)

,id_cliente,id_unico_cliente,prefixo_cep,cidade,estado
61106,c40005c07b1bdf1c39193476fa330f32,affe808d021cb4c3abf83a4c4aff36ea,16290,brauna,SP
20033,2472a0dcd32a7a004f34018c998ce7ee,5d86f8d85d7a325b8ad02dfc95d015cc,76980,vilhena,RO
31538,321ce37df9d56baeb8074da8de0b593a,7586515ee8846375909e8c9112dd0884,13170,sumare,SP
87994,acbe4b6adbc9282d11a7dd9e1cb784d6,ced2f2a9802448ab3c75ba63e5aa5877,70775,brasilia,DF
19462,7f8cc24b152f186008151ece0e99e383,d04f39740c64da524c9b78a588e5dabc,86181,cambe,PR

In [15]:
dataframe_clientes.describe()

,id_cliente,id_unico_cliente,prefixo_cep,cidade,estado
count,99441,99441,99441,99441,99441
unique,99441,96096,14994,4119,27
top,06b8999e2fba1a1fbc88172c00ba8bc7,8d50f5eadf50201ccdcedfb9e2ac8455,22790,sao paulo,SP
freq,1,17,142,15540,41746

In [16]:
from project_olist.config import PROCESSED_DATA_DIR

dataframe_clientes.to_csv(PROCESSED_DATA_DIR / "clientes.csv", index=False)