In [11]:
from project_olist.config import RAW_DATA_DIR
import pandas

dataframe_avaliacoes = pandas.read_csv(RAW_DATA_DIR / "olist_order_reviews_dataset.csv")
dataframe_avaliacoes = dataframe_avaliacoes.rename(
    columns={
        "review_id": "id_avaliacao",
        "order_id": "id_pedido",
        "review_score": "pontuacao",
        "review_creation_date": "data_criacao",
        "review_answer_timestamp": "data_resposta"
    }
)

dataframe_avaliacoes.info()

<class 'pandas.DataFrame'>
RangeIndex: 99224 entries, 0 to 99223
Data columns (total 7 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   id_avaliacao            99224 non-null  str
 1   id_pedido               99224 non-null  str
 2   pontuacao               99224 non-null  int64
 3   review_comment_title    11568 non-null  str
 4   review_comment_message  40977 non-null  str
 5   data_criacao            99224 non-null  str
 6   data_resposta           99224 non-null  str
dtypes: int64(1), str(6)
memory usage: 5.3 MB

In [12]:
dataframe_avaliacoes = dataframe_avaliacoes.drop_duplicates(subset="id_pedido")
dataframe_avaliacoes = dataframe_avaliacoes.drop_duplicates(subset="id_avaliacao")
dataframe_avaliacoes = dataframe_avaliacoes.reset_index(drop=True)

dataframe_avaliacoes.info()

<class 'pandas.DataFrame'>
RangeIndex: 98156 entries, 0 to 98155
Data columns (total 7 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   id_avaliacao            98156 non-null  str
 1   id_pedido               98156 non-null  str
 2   pontuacao               98156 non-null  int64
 3   review_comment_title    11509 non-null  str
 4   review_comment_message  40580 non-null  str
 5   data_criacao            98156 non-null  str
 6   data_resposta           98156 non-null  str
dtypes: int64(1), str(6)
memory usage: 5.2 MB

In [13]:
dataframe_avaliacoes = dataframe_avaliacoes.drop(
    columns=["review_comment_title", "review_comment_message"]
)

dataframe_avaliacoes.info()

<class 'pandas.DataFrame'>
RangeIndex: 98156 entries, 0 to 98155
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id_avaliacao   98156 non-null  str
 1   id_pedido      98156 non-null  str
 2   pontuacao      98156 non-null  int64
 3   data_criacao   98156 non-null  str
 4   data_resposta  98156 non-null  str
dtypes: int64(1), str(4)
memory usage: 3.7 MB

In [14]:
dataframe_avaliacoes.sample(n=5)

,id_avaliacao,id_pedido,pontuacao,data_criacao,data_resposta
19938,a6b0a15e1bd9a39d4b8ebca93d0d0e40,d849519c380fc7427ba88fc312ade389,1,2018-03-21 00:00:00,2018-03-21 19:01:07
20616,bcd56e5f560fd9577406dea28bc6158e,4d920656159629630f3cca4092065c72,4,2017-12-09 00:00:00,2017-12-11 15:26:49
37886,bcde63af6f45ec9f13613ddc1f1a6391,96eb3b1e9be34336c89369e6efa182f5,5,2018-02-10 00:00:00,2018-02-14 17:31:22
52603,05af9f5e7b145509dffdf39d173e47b8,dbf8b46f6dad6cd41ed7e06b5dcbf4d1,5,2017-05-11 00:00:00,2017-05-14 00:05:09
91498,fa2707dc378e5d35f1988e6cb4b59b29,02610d88ac343ed64988d2706ce3ebfd,5,2018-02-23 00:00:00,2018-02-23 22:49:27

In [15]:
dataframe_avaliacoes["data_criacao"] = pandas.to_datetime(dataframe_avaliacoes["data_criacao"]).dt.normalize()
dataframe_avaliacoes["data_resposta"] = pandas.to_datetime(dataframe_avaliacoes["data_resposta"]).dt.normalize()

dataframe_avaliacoes.info()

<class 'pandas.DataFrame'>
RangeIndex: 98156 entries, 0 to 98155
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id_avaliacao   98156 non-null  str
 1   id_pedido      98156 non-null  str
 2   pontuacao      98156 non-null  int64
 3   data_criacao   98156 non-null  datetime64[us]
 4   data_resposta  98156 non-null  datetime64[us]
dtypes: datetime64[us](2), int64(1), str(2)
memory usage: 3.7 MB

In [16]:
dataframe_avaliacoes["tempo_resposta_dias"] = (
    (dataframe_avaliacoes["data_resposta"] - dataframe_avaliacoes["data_criacao"]).dt.days
)

dataframe_avaliacoes.sample(n=5)

,id_avaliacao,id_pedido,pontuacao,data_criacao,data_resposta,tempo_resposta_dias
62674,696b2f9fee06062cc683f4a1958bf674,12e4fbad3ebed6412967a3fd5818c456,5,2018-06-23,2018-06-24,1
69044,7f5aa387d15c7a7f89a054e8f0599acd,04378b376807e5fbc797362f9e06ea2d,5,2018-04-25,2018-04-26,1
75869,f188e279452a4580396ad1690dd43ecd,3482fd5db03ecb3857123956a9eeb1a0,5,2018-05-22,2018-05-24,2
32076,b4d8714967194ff94480fe6647469847,45881bf836d74c8e321eb6467c8eef47,5,2018-03-01,2018-03-02,1
64201,bb82aebfd3d4dabe9f9432ae0cebcc05,afa91e78effcc9fbc392951b0184f11a,5,2017-06-15,2017-06-15,0

In [17]:
dataframe_avaliacoes = dataframe_avaliacoes.drop(
    columns=[
        "data_criacao",
        "data_resposta"
    ]
)

dataframe_avaliacoes.info()

<class 'pandas.DataFrame'>
RangeIndex: 98156 entries, 0 to 98155
Data columns (total 4 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   id_avaliacao         98156 non-null  str
 1   id_pedido            98156 non-null  str
 2   pontuacao            98156 non-null  int64
 3   tempo_resposta_dias  98156 non-null  int64
dtypes: int64(2), str(2)
memory usage: 3.0 MB

In [18]:
dataframe_avaliacoes.describe()

          pontuacao  tempo_resposta_dias
count  98156.000000         98156.000000
mean       4.088808             2.584916
std        1.345704             9.926919
min        1.000000             0.000000
25%        4.000000             1.000000
50%        5.000000             1.000000
75%        5.000000             3.000000
max        5.000000           518.000000

In [19]:
dataframe_avaliacoes["cliente_satisfeito"] = dataframe_avaliacoes.apply(
    lambda row: (
        1 if row["pontuacao"] >= 4
        else 0
    ),
    axis=1
)

In [20]:
from project_olist.config import PROCESSED_DATA_DIR

dataframe_avaliacoes.to_csv(PROCESSED_DATA_DIR / "avaliacoes.csv", index=False)