In [44]:
from project_olist.config import RAW_DATA_DIR
import pandas

dataframe_geolocalizacoes = pandas.read_csv(RAW_DATA_DIR / "olist_geolocation_dataset.csv")
dataframe_geolocalizacoes = dataframe_geolocalizacoes.rename(
    columns={
        "geolocation_zip_code_prefix": "prefixo_cep",
        "geolocation_lat": "latitude",
        "geolocation_lng": "longitude",
        "geolocation_city": "cidade",
        "geolocation_state": "estado"
    }
)

dataframe_geolocalizacoes.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000163 entries, 0 to 1000162
Data columns (total 5 columns):
 #   Column       Non-Null Count    Dtype
---  ------       --------------    -----
 0   prefixo_cep  1000163 non-null  int64
 1   latitude     1000163 non-null  float64
 2   longitude    1000163 non-null  float64
 3   cidade       1000163 non-null  str
 4   estado       1000163 non-null  str
dtypes: float64(2), int64(1), str(2)
memory usage: 38.2 MB

In [45]:
dataframe_geolocalizacoes["prefixo_cep"] = dataframe_geolocalizacoes["prefixo_cep"].astype(str)
dataframe_geolocalizacoes["prefixo_cep"] = dataframe_geolocalizacoes["prefixo_cep"].map(
    lambda x: x.rjust(5, "0")
)

In [46]:
dataframe_geolocalizacoes.sample(n=5)

       prefixo_cep   latitude  longitude         cidade estado
92979        04542 -23.588898 -46.683129      sao paulo     SP
704880       49072 -10.899449 -37.063024        aracaju     SE
541346       29950 -18.904801 -40.071586        jaguare     ES
964294       95084 -29.175478 -51.190733  caxias do sul     RS
853867       81810 -25.514481 -49.280460       curitiba     PR

In [47]:
dataframe_geolocalizacoes.describe()

           latitude     longitude
count  1.000163e+06  1.000163e+06
mean  -2.117615e+01 -4.639054e+01
std    5.715866e+00  4.269748e+00
min   -3.660537e+01 -1.014668e+02
25%   -2.360355e+01 -4.857317e+01
50%   -2.291938e+01 -4.663788e+01
75%   -1.997962e+01 -4.376771e+01
max    4.506593e+01  1.211054e+02

In [48]:
dataframe_geolocalizacoes = dataframe_geolocalizacoes.groupby(by="prefixo_cep", as_index=False).agg(
    {
        "latitude": "mean",
        "longitude": "mean",
        "cidade": "first",
        "estado": "first"
    }
)

In [49]:
dataframe_geolocalizacoes.describe()

           latitude     longitude
count  19015.000000  19015.000000
mean     -19.055250    -46.057645
std        7.295792      5.365775
min      -33.689948    -72.916069
25%      -23.564143    -49.001737
50%      -22.416053    -46.631931
75%      -15.612108    -43.255374
max       42.184003    121.105394

In [50]:
from project_olist.config import PROCESSED_DATA_DIR

dataframe_geolocalizacoes.to_csv(PROCESSED_DATA_DIR / "geolocalizacoes.csv", index=False)